# Generated by Django 5.0.6 on 2024-06-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        default="какое-либо место",
                        max_length=200,
                        verbose_name="место выполнения",
                    ),
                ),
                (
                    "time_execute",
                    models.TimeField(
                        default="00:00:00", verbose_name="время на выполнение"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        default="новые действия",
                        max_length=200,
                        verbose_name="действие",
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False, verbose_name="приятность привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="периодичность выполнения (в днях)"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_duration",
                    models.PositiveSmallIntegerField(
                        default="60", verbose_name="время на выполнение в секундах"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="признак публичности"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": ("привычка",),
                "verbose_name_plural": "привычки",
                "ordering": ("id",),
            },
        ),
    ]
